In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch  

a = torch.ones(3)  
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [19]:
points_storage = points.storage()
points_storage[0]

4.0

In [20]:
points.storage()[1]

1.0

In [23]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [24]:
short_points.dtype

torch.int16

In [25]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [26]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [27]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [28]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [29]:
points_storage = points.storage()
points_storage[0]

4.0

In [30]:
points.storage()[1]

1.0

In [32]:
# 2次元テンソルを作成（3点の座標）
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])  # shape: (3, 2)

# Tensorの内部ストレージ（1次元）を取得
points_storage = points.storage()

# ストレージの最初の要素（0番目）を書き換え（メモリの中身を直接操作）
points_storage[0] = 2.0

# points自体も変更されている（ストレージ共有のため）
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [33]:
# 3点の2次元座標を含むテンソルを作成（shape: [3, 2]）
points = torch.tensor(
    [[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]  # index 0  # index 1 ← これを取得  # index 2
)

# 2番目の点（[5.0, 3.0]）を取得
second_point = points[1]  # shape: [2]

# second_point のストレージにおける**先頭位置のインデックス（オフセット）**を取得
second_point.storage_offset()

2

In [34]:
second_point.size()

torch.Size([2])

In [35]:
second_point.shape

torch.Size([2])

In [36]:
points.stride()

(2, 1)

In [40]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [39]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [41]:
points_t = points.t()
points_t

tensor([[ 4., 10.,  2.],
        [ 1.,  3.,  1.]])

In [43]:
# 2つのテンソルが同じストレージ（物理メモリ領域）を共有しているかを確認する

# points と points_t は例えば以下のように定義されているとする：
# points = torch.tensor([[1., 2.], [3., 4.]])
# points_t = points.t()  # 転置ビュー：メモリ共有される

# id(...) はPythonの組み込み関数で、オブジェクトの識別番号（＝メモリアドレス）を返す
# .storage() はテンソルの元となる1次元ストレージを返す

# ここでは、両者のストレージオブジェクトが同一かどうかを id 比較で確認している
id(points.storage()) == id(points_t.storage())  # Trueなら同一のメモリを共有している

True

In [44]:
points.stride()

(2, 1)

In [45]:
points_t.stride()

(1, 2)

In [46]:
# 元テンソルを作成：すべて1のテンソル（形状: [3, 4, 5]）
some_t = torch.ones(3, 4, 5)

# 転置操作：0番目（最初）と2番目（最後）の次元を入れ替える
# 元の shape: [0, 1, 2] = [3, 4, 5]
# 新しい shape: [2, 1, 0] = [5, 4, 3]
transpose_t = some_t.transpose(0, 2)

# 元のテンソルの形状を確認（転置しても some_t 自体は変化しない）
some_t.shape  # → torch.Size([3, 4, 5])

torch.Size([3, 4, 5])

In [47]:
transpose_t.shape

torch.Size([5, 4, 3])

In [48]:
some_t.stride()

(20, 5, 1)

In [49]:
transpose_t.stride()

(1, 5, 20)

In [50]:
# points は新規作成されたテンソルなので常に contiguous（連続メモリ配置）
points.is_contiguous()  # → True

True

In [51]:
# points_t は view（転置）で作られており、メモリの順序が変化したため通常は非contiguous
points_t.is_contiguous()  # → False

False

In [52]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [53]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [54]:
points_t.stride()

(1, 2)

In [55]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [56]:
points_t_cont.stride()

(3, 1)

In [57]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [59]:
import torch
torch.backends.mps.is_available()

True

In [60]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="mps")

In [61]:
points_gpu = points.to(device="mps")

In [62]:
points_gpu = points.to(device="mps:0")

In [ ]:
points = 2 * points
points_gpu = 2 * points.to(device="mps")

In [64]:
points_gpu = points_gpu + 4

In [65]:
points_cpu = points_gpu.to(device='mps')

In [66]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [67]:
points = torch.from_numpy(points_np)